# Generated by Django 2.2.10 on 2020-03-21 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_auto_20200321_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs_details1',
            new_name='Jobs_details',
        ),
    ]
