# Generated by Django 2.2.10 on 2020-03-23 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_auto_20200321_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs_details1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=50)),
                ('last_date', models.DateField()),
                ('company', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('imgSrc', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Jobs_details',
        ),
    ]
