# Generated by Django 2.2.10 on 2020-03-23 08:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_auto_20200323_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs_details1',
            new_name='Jobs_details',
        ),
    ]
