# Generated by Django 2.2.10 on 2020-07-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200323_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs_details',
            name='last_date',
            field=models.CharField(max_length=10),
        ),
    ]
