# Generated by Django 2.2.10 on 2020-07-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20200716_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs_details',
            name='last_date',
            field=models.DateTimeField(max_length=10),
        ),
    ]
