# Generated by Django 2.2.10 on 2020-07-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200708_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
