# Generated by Django 2.2.10 on 2020-07-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200708_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conditions',
            field=models.BooleanField(default=False),
        ),
    ]
