# Generated by Django 2.2.10 on 2020-07-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_linkedin_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedin_model',
            name='currentLocation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='linkedin_model',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='linkedin_model',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='linkedin_model',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
