# Generated by Django 2.2.9 on 2020-02-24 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyForm_queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_message', models.CharField(default='', max_length=1154)),
                ('contactform', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contactform.ContactForm_queries')),
            ],
        ),
        migrations.AddField(
            model_name='contactform_queries',
            name='replyform',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='contactform.ReplyForm_queries'),
        ),
    ]
