# Generated by Django 2.2.9 on 2020-03-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyForm_queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=54)),
                ('subject', models.CharField(max_length=54)),
                ('reply_message', models.CharField(max_length=1154)),
                ('query_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactform.ContactForm_queries')),
            ],
        ),
    ]
