# Generated by Django 2.2.9 on 2020-03-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_replyform_queries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replyform_queries',
            name='email',
        ),
        migrations.RemoveField(
            model_name='replyform_queries',
            name='subject',
        ),
    ]
