# Generated by Django 2.2.9 on 2020-02-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0003_auto_20200224_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform_queries',
            name='replyform',
        ),
    ]
