# Generated by Django 2.2.9 on 2020-02-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0004_remove_contactform_queries_replyform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replyform_queries',
            name='contactform',
        ),
        migrations.AddField(
            model_name='replyform_queries',
            name='email',
            field=models.CharField(default='email+default', max_length=54),
        ),
        migrations.AddField(
            model_name='replyform_queries',
            name='message',
            field=models.CharField(default='message+default', max_length=1154),
        ),
        migrations.AddField(
            model_name='replyform_queries',
            name='name',
            field=models.CharField(default='name+default', max_length=50),
        ),
        migrations.AddField(
            model_name='replyform_queries',
            name='subject',
            field=models.CharField(default='subject+default', max_length=54),
        ),
        migrations.AlterField(
            model_name='replyform_queries',
            name='reply_message',
            field=models.CharField(max_length=1154),
        ),
    ]
