# Generated by Django 2.2.9 on 2020-02-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0005_auto_20200224_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyform_queries',
            name='email',
            field=models.EmailField(default='email+default', max_length=54),
        ),
    ]
