# Generated by Django 3.0.5 on 2020-07-16 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonatorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('date_donated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
