# Generated by Django 3.0.5 on 2020-07-16 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donatorinfo',
            old_name='d_name',
            new_name='donator_name',
        ),
    ]
